version: "3.8"
services:
  db:
    container_name: mysql
    image: megan1999/trio-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
    volumes:
      - type: volume
        source: trio-db-volume
        target: /var/lib/mysql
    build: ./db
  flask-app:
    container_name: flask-app
    image: megan1999/trio-task-flask-app
    build: ./db
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

volumes:
  trio-db-volume: